// THIS FILE IS EMPTY ON MASTER AND ONLY AS A PLACEHOLDER HERE
// MERGES TO THIS FILE ARE FORBIDDEN IN .gitattributes
// YOU CAN MODIFY THIS FILE IN FEATURE BRANCHES TO TEST ROUTES
export default function TestNavigation () {
    return null
}